#!/bin/sh
if test "$(which apm)"; then
  apm upgrade --confirm false

  modules="
    advanced-open-file
    atom-beautify
    atom-dark-fusion-syntax
    atom-material-syntax
    atom-material-ui
    atomatigit
    busy-signal
    color-picker
    diagrams
    easy-motion-redux
    emmet-simplified
    ex-mode
    expand-region
    file-icons
    git-blame
    git-plus
    git-time-machine
    go-debug
    go-plus
    go-rename
    go-signature-statusbar
    golden-ratio
    highlight-line
    hyperclick
    intentions
    language-babel
    language-diff
    language-docker
    language-dot
    language-eco
    language-groovy
    language-liquid
    language-powershell
    language-rspec
    language-rust
    language-swift
    lines
    linter
    linter-docker
    linter-eslint
    linter-flow
    linter-rubocop
    linter-ruby
    linter-swagger
    linter-ui-default
    markdown-preview-enhanced
    markdown-table-formatter
    maximize-panes
    merge-conflicts
    move-panes
    nucleus-dark-ui
    oceanic-next
    predawn-syntax
    predawn-ui
    pretty-json
    project-manager
    recent-files-fuzzy-finder
    rspec
    rubocop-auto-correct
    symbol-gen
    tab-switcher
    vim-mode-plus
    vim-mode-plus-ex-mode
  "
  for module in $modules; do
    # apm install "$module" || true
  done
fi
