#!/bin/zsh
set -e

# Lint files
./build/build.sh

# link to ~ and cd to it
cd ..
cp -rf dotfiles ~/.dotfiles
cd ~/.dotfiles

# setup git credentials
git config --global user.name "dotfiles demo"
git config --global user.email "dotfiles@demo.com"

# bootstrap the mighty
echo 'running ./script/bootstrap...'
./script/bootstrap

source ~/.zshrc

antibody list

# test $(antibody list | wc -l) -gt 5 || {
#   echo "expecting 5+ bundles loaded" >&2
#   exit 1
# }
#
# test -s ~/.zcompdump || {
#   echo "zcompdump file is empty" >&2
#   exit 1
# }
#
# echo 'Tests passed!'
