#!/bin/zsh
set -e

# Lint files
./build/build.sh

# link to ~ and cd to it
cd ..
cp -rf dotfiles ~/.dotfiles
cd ~/.dotfiles

# setup git credentials
git config --global user.name "dotfiles demo"
git config --global user.email "dotfiles@demo.com"

# bootstrap the mighty
echo 'running ./script/bootstrap...'
./script/bootstrap
# echo 'done running ./script/bootstrap...'
#
# # load zshrc and check if antibody is working
# echo 'sourcing ~/.zshrc...'
# source ~/.zshrc || {
#   echo "error sourcing ~/.zshrc" >&2
#   exit 1
# }
# echo 'done sourcing ~/.zshrc'

test $(antibody list | wc -l) -gt 5 || {
  echo "expecting 5+ bundles loaded" >&2
  exit 1
}

test -s ~/.zcompdump || {
  echo "zcompdump file is empty" >&2
  exit 1
}

echo 'Tests passed!'
