#!/bin/zsh
set -e

# Lint files
./build/build.sh

# link to ~ and cd to it
cd ..
cp -rf dotfiles ~/.dotfiles
cd ~/.dotfiles

# setup git credentials
git config --global user.name "dotfiles demo"
git config --global user.email "dotfiles@demo.com"

# bootstrap the mighty
./script/bootstrap

# load zshrc and check if antidote is working
source ~/.zshrc

test $(antidote list | wc -l) -gt 4 || {
  echo "expecting 4+ bundles loaded" >&2
  exit 1
}

test -s ~/.zcompdump || {
  echo "zcompdump file is empty" >&2
  exit 1
}
