return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "bash",
      "c",
      "css",
      "diff",
      "dockerfile",
      "git_rebase",
      "gitcommit",
      "gitignore",
      "go",
      "gomod",
      "graphql",
      "hcl",
      "html",
      "javascript",
      "json",
      "lua",
      "make",
      "markdown",
      "ruby",
      "sql",
      "tsx",
      "typescript",
      "vim",
      "yaml",
    },
    auto_install = true,
  }
}
